### PR TITLE
Change to gender-neutral singular _they_ as pronoun

### PR DESCRIPTION
**Pull request by norpol**
Hi,
I hope this pull request is appreciated.
Please reread before merging, as I'm not an English native might be something wrong now. Also I might still be missing something after `sed`ing.

Thank you.

### CODE REVIEW

**Comment by d33tah** [comment]
@norpol Hi! Have a look at this rich diff:

https://github.com/d33tah/call-for-wpa3/pull/10/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

Looks like it should be "they please" instead of "they pleases".

**Comment by norpol** [comment]
I think it's alright - might read maybe weird at first, but it's singular.

> Anyone that is connected to the network can effectively read everyone's traffic and change it as they pleases.

**Comment by TPS** [comment]
It's singular, but still follows [plural grammar](https://en.m.wikipedia.org/wiki/Singular_they#Usage_guidance_in_English_grammars).

**Comment by norpol** [comment]
Thank you, will update tonight.

**Comment by norpol** [comment]
Hopefully alright now. Thank's for pointing out again.

**Pull request merged**
